# Resources for AlpLevelDefaults class (ALP site plan level names)
defaultLevelName=Plan
layerName=Layer {0}
referenceLevelName=Reference
existingLevelName=Existing
proposedLevelName=Proposed
plantsLevelName=Plants
annotationsLevelName=Annotations
