# Resources for LevelCategory enum (SPIKE-30)
LevelCategory.general.label=General
LevelCategory.reference.label=Reference
LevelCategory.site.label=Site
LevelCategory.planting.label=Planting
LevelCategory.annotation.label=Annotation
